name: Build and deploy
on:
  push:
    branches:
      - develop
      - feature/expand-page
jobs:
  build:
    uses: ./.github/workflows/build-image.yml

  deploy:
    uses: ./.github/workflows/deploy.yml
