---

name: Deploy doc in production

on:
  push:
    branches:
      - main

concurrency: deploy-doc

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Define cache_id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Setup cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install python requirements.txt
        run: pip install -r requirements.txt

      - name: Build doc
        run: mkdocs build

      - name: Clone branch gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages  # clone in $GITHUB_WORKSPACE/gh-pages/

      - name: Copy build results
        run: |
          rsync -av \
            --delete \
            --checksum \
            --exclude .git/ \
            --exclude pr-preview/ \
            site/ $GITHUB_WORKSPACE/gh-pages/

      - name: Commit and push
        run: |
          cd $GITHUB_WORKSPACE/gh-pages/
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Auto build/deploy docs from main branch"
          git push --force origin gh-pages
