name: Deploy
on:
  workflow_call:
    inputs:
      version:
        description: Version of the docker image to deploy
        type: string
        required: false
        default: devel
  workflow_dispatch:
    inputs:
      version:
        description: Version of the docker image to deploy
        type: string
        required: false
        default: devel

jobs:
  deploy:
    name: Deployment
    runs-on: [ self-hosted, linux, domain=sb ]
    steps:
      - name: Write config
        uses: DamianReeves/write-file-action@master
        with:
          path: docs.hcl
          write-mode: overwrite
          contents: |
            job "docs" {
              datacenters = [ "dc1" ]
              type        = "service"
              priority    = 100

              group "docs" {
                network {
                  port "http" { to = 8000 }
                }

                task "docs" {
                  driver = "docker"
                  config {
                    image      = "docker.strangebee.com/strangebee/docs${{ endsWith(inputs.version, 'sha256') && '@' || ':' }}${{ inputs.version }}"
                    force_pull = true
                    ports      = [ "http" ]
                  }

                  service {
                    name     = "docs"
                    provider = "consul"
                    port     = "http"
                    tags     = [
                      "traefik.enable=true",
                      "traefik.http.routers.docs.entrypoints=http,https",
                      "traefik.http.routers.docs.rule=Host(`docs.web.dev.sb`)"
                    ]
                  }

                  resources {
                    cpu    = 200
                    memory = 256
                  }  
                }
              }
            }

      - name: setup vault token
        run: echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV

      - name: Get nomad token
        uses: hashicorp/vault-action@v2
        id: vault
        with:
          url: https://vault.service.infra.sb:8200
          token: ${{ env.VAULT_TOKEN }}
          caCertificate: ${{ secrets.VAULT_CA_CERT }}
          tlsSkipVerify: true
          secrets: |
            /nomad-dev/creds/developers-token-dev secret_id | NOMAD_TOKEN;

      - name: Deploy with Levant on Nomad
        uses: docker://hashicorp/levant
        env:
          NOMAD_ADDR: http://10.30.4.180:4646
        with:
          args: deploy -force docs.hcl
        continue-on-error: true